services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.compose
  valkey:
    image: valkey/valkey:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
  mailer:
    image: mailtutan/mailtutan:latest
    restart: unless-stopped
    ports:
      - 1080:1080
      - 1025:1025
volumes:
  postgres-data: